; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_metro_esp32s2]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = adafruit_metro_esp32s2
framework = arduino
board_build.partitions = min_spiffs.csv
lib_deps = 
	tzapu/WiFiManager@^2.0.17
	matth-x/MicroOcpp@^1.2.0
	miguelbalboa/MFRC522@^1.4.12

#upload_protocol = espota
#upload_port = 192.168.8.240
#upload_flags = 
#	--auth=admin
